### ISSUE TITLE
`drush qd --makefile=build-farm.make` fails

### ISSUE THREAD

**Issue by rjcorwin** [farmOS/farmOS#4]
```
 /.../Desktop/farmos ♘ drush qd --help | less
 /.../Desktop/farmos ♘ git clone git@github.com:farmOS/farm.git
Cloning into 'farm'...
remote: Counting objects: 716, done.
remote: Total 716 (delta 0), reused 0 (delta 0), pack-reused 716
Receiving objects: 100% (716/716), 106.09 KiB | 0 bytes/s, done.
Resolving deltas: 100% (444/444), done.
Checking connectivity... done.
 /.../Desktop/farmos ♘ cd farm/
 /.../farmos/farm[7.x-1.x] ♘ ls
README.md       build-farm.make     drupal-org-core.make    drupal-org.make     farm.info       farm.install        farm.profile
 /.../farmos/farm[7.x-1.x] ♘ drush qd --make=build-farm.make
Unknown option: --make.  See `drush help core-quick-drupal` for available options. To suppress this error, add the option --strict=0.                                     [error]
 /.../farmos/farm[7.x-1.x] ♘ drush qd --makefile=build-farm.make
Beginning to build build-farm.make.                                                                                                                                       [ok]
drupal-7.41 downloaded.                                                                                                                                                   [ok]
drupal patched with php_5_5_imagerotate-2215369-51.patch.                                                                                                                 [ok]
Generated PATCHES.txt file for drupal                                                                                                                                     [ok]
farm cloned from http://github.com/farmOS/farm.git.                                                                                                                       [ok]
Checked out branch 7.x-1.x.                                                                                                                                               [ok]
Found makefile: drupal-org.make                                                                                                                                           [ok]
colorbox-7.x-2.10 downloaded.                                                                                                                                             [ok]
Found makefile: colorbox.make                                                                                                                                             [ok]
colorbox downloaded from https://github.com/jackmoore/colorbox/archive/1.x.zip.                                                                                           [ok]
Project ctools contains 10 modules: views_content, term_depth, stylizer, page_manager, ctools_plugin_example, ctools_custom_content, ctools_ajax_sample, ctools_access_ruleset, bulk_export, ctools.
ctools-7.x-1.9 downloaded.                                                                                                                                                [ok]
ctools patched with eventBubblingBugIE8-1823088-9.patch.                                                                                                                  [ok]
Generated PATCHES.txt file for ctools                                                                                                                                     [ok]
Project date contains 11 modules: date_views, date_tools, date_repeat_field, date_repeat, date_popup, date_migrate_example, date_migrate, date_context, date_api, date_all_day, date.
date-7.x-2.9 downloaded.                                                                                                                                                  [ok]
Project entity contains 2 modules: entity, entity_token.
entity-7.x-1.6 downloaded.                                                                                                                                                [ok]
Project entityreference contains 2 modules: entityreference_behavior_example, entityreference.
entityreference-7.x-1.1 downloaded.                                                                                                                                       [ok]
entityreference_view_widget-7.x-2.0-rc6 downloaded.                                                                                                                       [ok]
entityreference_view_widget patched with entityreference_view_widget_suffix-2524296-2.patch.                                                                              [ok]
Generated PATCHES.txt file for entityreference_view_widget                                                                                                                [ok]
exif_orientation-7.x-1.0 downloaded.                                                                                                                                      [ok]
features-7.x-2.7 downloaded.                                                                                                                                              [ok]
field_collection-7.x-1.0-beta9 downloaded.                                                                                                                                [ok]
filefield_paths-7.x-1.0-rc1 downloaded.                                                                                                                                   [ok]
fraction-7.x-1.2 downloaded.                                                                                                                                              [ok]
geocoder-7.x-1.2 downloaded.                                                                                                                                              [ok]
geocoder patched with geocoder_multivalue_filefields-2352887-1.patch.                                                                                                     [ok]
geocoder patched with geocoder_kmz-2352931-2.patch.                                                                                                                       [ok]
Generated PATCHES.txt file for geocoder                                                                                                                                   [ok]
Project geofield contains 2 modules: geofield_map, geofield.
geofield-7.x-2.3 downloaded.                                                                                                                                              [ok]
geofield patched with geofield-delete_feature_fix-1350320-20.patch.                                                                                                       [ok]
Generated PATCHES.txt file for geofield                                                                                                                                   [ok]
geophp-7.x-1.7 downloaded.                                                                                                                                                [ok]
jquery_update-7.x-3.0-alpha3 downloaded.                                                                                                                                  [ok]
libraries-7.x-2.2 downloaded.                                                                                                                                             [ok]
libraries_cdn-7.x-1.7 downloaded.                                                                                                                                         [ok]
Project log contains 2 modules: log_plan, log.
log-7.x-1.0 downloaded.                                                                                                                                                   [ok]
Project logintoboggan contains 4 modules: logintoboggan_variable, logintoboggan_rules, logintoboggan_content_access_integration, logintoboggan.
logintoboggan-7.x-1.5 downloaded.                                                                                                                                         [ok]
navbar-7.x-1.6 downloaded.                                                                                                                                                [ok]
openlayers cloned from http://git.drupal.org/project/openlayers.git.                                                                                                      [ok]
Checked out revision deee17fd3bf605a273f2bfacca40b84aa1993c65.                                                                                                            [ok]
openlayers patched with openlayers_googlemaps_postbuild-2538168-5.patch.                                                                                                  [ok]
openlayers patched with openlayers_base_layer_mechanism-2543130-4.patch.                                                                                                  [ok]
openlayers patched with openlayers_google_maps_tilt_0-2573005-1.patch.                                                                                                    [ok]
Generated PATCHES.txt file for openlayers                                                                                                                                 [ok]
date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case[warning]
you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but
please set date.timezone to select your timezone. pm.drush.inc:2212
openlayers_geolocate_button-7.x-3.1 downloaded.                                                                                                                           [ok]
Project panels contains 5 modules: panels_node, panels_mini, panels_ipe, i18n_panels, panels.
panels-7.x-3.5 downloaded.                                                                                                                                                [ok]
pathauto-7.x-1.3 downloaded.                                                                                                                                              [ok]
pathauto_entity-7.x-1.0 downloaded.                                                                                                                                       [ok]
registry_autoload-7.x-1.3 downloaded.                                                                                                                                     [ok]
Project restws contains 2 modules: restws_basic_auth, restws.
restws-7.x-2.4 downloaded.                                                                                                                                                [ok]
role_delegation-7.x-1.1 downloaded.                                                                                                                                       [ok]
Project service_container contains 4 modules: service_container_block, service_container_symfony, service_container_annotation_discovery, service_container.
service_container-7.x-1.0-beta5 downloaded.                                                                                                                               [ok]
strongarm-7.x-2.0 downloaded.                                                                                                                                             [ok]
token-7.x-1.6 downloaded.                                                                                                                                                 [ok]
Project views contains 2 modules: views, views_ui.
views-7.x-3.11 downloaded.                                                                                                                                                [ok]
views patched with views_with_exposed-1809958-28.patch.                                                                                                                   [ok]
Generated PATCHES.txt file for views                                                                                                                                      [ok]
Project views_bulk_operations contains 2 modules: actions_permissions, views_bulk_operations.
views_bulk_operations-7.x-3.3 downloaded.                                                                                                                                 [ok]
views_data_export-7.x-3.0-beta8 downloaded.                                                                                                                               [ok]
views_geojson-7.x-1.0-beta2 downloaded.                                                                                                                                   [ok]
views_geojson patched with views_geojson_relative_source_url-2543622-1.patch.                                                                                             [ok]
Generated PATCHES.txt file for views_geojson                                                                                                                              [ok]
views_tree-7.x-2.0 downloaded.                                                                                                                                            [ok]
backup_migrate-7.x-3.1 downloaded.                                                                                                                                        [ok]
Project devel contains 3 modules: devel_generate, devel, devel_node_access.
devel-7.x-1.5 downloaded.                                                                                                                                                 [ok]
diff-7.x-3.2 downloaded.                                                                                                                                                  [ok]
module_filter-7.x-2.0 downloaded.                                                                                                                                         [ok]
farm_access-7.x-1.0 downloaded.                                                                                                                                           [ok]
farm_admin-7.x-1.0-beta6 downloaded.                                                                                                                                      [ok]
farm_area-7.x-1.0-beta6 downloaded.                                                                                                                                       [ok]
farm_asset-7.x-1.0-beta6 downloaded.                                                                                                                                      [ok]
farm_crop-7.x-1.0-beta6 downloaded.                                                                                                                                       [ok]
farm_equipment-7.x-1.0-beta6 downloaded.                                                                                                                                  [ok]
farm_fields-7.x-1.0-beta1 downloaded.                                                                                                                                     [ok]
Project farm_livestock contains 2 modules: farm_livestock_eggs, farm_livestock.
farm_livestock-7.x-1.0-beta6 downloaded.                                                                                                                                  [ok]
farm_log-7.x-1.0-beta6 downloaded.                                                                                                                                        [ok]
farm_map-7.x-1.0-beta6 downloaded.                                                                                                                                        [ok]
farm_mapknitter-7.x-1.1 downloaded.                                                                                                                                       [ok]
farm_sensor-7.x-1.0-beta3 downloaded.                                                                                                                                     [ok]
Project farm_soil contains 2 modules: farm_soil_test, farm_soil.
farm_soil-7.x-1.0-beta6 downloaded.                                                                                                                                       [ok]
farm_taxonomy-7.x-1.0-beta4 downloaded.                                                                                                                                   [ok]
bootstrap-7.x-3.1-beta3 downloaded.                                                                                                                                       [ok]
bootstrap patched with bootstrap_panel_element_id-2468625-7.patch.                                                                                                        [ok]
bootstrap patched with bootstrap_fluid_container_default-2556603-1.patch.                                                                                                 [ok]
Generated PATCHES.txt file for bootstrap                                                                                                                                  [ok]
farm_theme-7.x-1.0-beta6 downloaded.                                                                                                                                      [ok]
backbone downloaded from http://github.com/jashkenas/backbone/archive/1.1.2.zip.                                                                                          [ok]
modernizr downloaded from http://github.com/Modernizr/Modernizr/archive/v2.8.3.zip.                                                                                       [ok]
underscore downloaded from http://github.com/jashkenas/underscore/archive/1.7.0.zip.                                                                                      [ok]
You are about to create a /Users/rjsteinert/Desktop/farmos/farm/quick-drupal-20151024182516/drupal/sites/default/settings.php file and CREATE the 'Users/rjsteinert/Desktop/farmos/farm/quick-drupal-20151024182516/quick-drupal-20151024182516.sqlite' database. Do you want to continue? (y/n): y
Starting Drupal installation. This takes a while. Consider using the --notify global option.                                                                              [ok]
exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1 there is already an index named log_type' in                                                     [error]
/Users/rjsteinert/Desktop/farmos/farm/quick-drupal-20151024182516/drupal/includes/database/sqlite/database.inc:238
Stack trace:
#0 /Users/rjsteinert/Desktop/farmos/farm/quick-drupal-20151024182516/drupal/includes/database/sqlite/database.inc(238): PDO->prepare('CREATE TABLE lo...', Array)
#1 /Users/rjsteinert/Desktop/farmos/farm/quick-drupal-20151024182516/drupal/includes/database/sqlite/database.inc(456): DatabaseConnection_sqlite->PDOPrepare('CREATE
TABLE lo...')
#2 /Users/rjsteinert/Desktop/farmos/farm/quick-drupal-20151024182516/drupal/includes/database/prefetch.inc(163): DatabaseStatement_sqlite->getStatement('CREATE TABLE
lo...', Array)
#3 /Users/rjsteinert/Desktop/farmos/farm/quick-drupal-20151024182516/drupal/includes/database/sqlite/database.inc(461): DatabaseStatementPrefetch->execute(Array, Array)
#4 /Users/rjsteinert/Desktop/farmos/farm/quick-drupal-20151024182516/drupal/includes/database/database.inc(683): DatabaseStatement_sqlite->execute(Array, Array)
#5 /Users/rjsteinert/Desktop/farmos/farm/quick-drupal-20151024182516/drupal/includes/database/schema.inc(664): DatabaseConnection->query('CREATE TABLE {l...')
#6 /Users/rjsteinert/Desktop/farmos/farm/quick-drupal-20151024182516/drupal/includes/database/database.inc(2720): DatabaseSchema->createTable('log_type', Array)
#7 /Users/rjsteinert/Desktop/farmos/farm/quick-drupal-20151024182516/drupal/includes/common.inc(7064): db_create_table('log_type', Array)
#8 /Users/rjsteinert/Desktop/farmos/farm/quick-drupal-20151024182516/drupal/includes/module.inc(462): drupal_install_schema('log')
#9 /Users/rjsteinert/Desktop/farmos/farm/quick-drupal-20151024182516/drupal/includes/install.core.inc(1602): module_enable(Array, false)
#10 [internal function]: _install_module_batch('log', 'Log', Array)
#11 /Users/rjsteinert/Desktop/farmos/farm/quick-drupal-20151024182516/drupal/includes/batch.inc(284): call_user_func_array('_install_module...', Array)
#12 /Users/rjsteinert/Desktop/farmos/farm/quick-drupal-20151024182516/drupal/includes/form.inc(4704): _batch_process()
#13 /Users/rjsteinert/Desktop/farmos/farm/quick-drupal-20151024182516/drupal/includes/install.core.inc(444): batch_process('install.php?pro...', 'http://default/...')
#14 /Users/rjsteinert/Desktop/farmos/farm/quick-drupal-20151024182516/drupal/includes/install.core.inc(339): install_run_task(Array, Array)
#15 /Users/rjsteinert/Desktop/farmos/farm/quick-drupal-20151024182516/drupal/includes/install.core.inc(77): install_run_tasks(Array)
#16 /Users/rjsteinert/.composer/vendor/drush/drush/includes/drush.inc(720): install_drupal(Array)
#17 /Users/rjsteinert/.composer/vendor/drush/drush/includes/drush.inc(706): drush_call_user_func_array('install_drupal', Array)
#18 /Users/rjsteinert/.composer/vendor/drush/drush/commands/core/drupal/site_install_7.inc(80): drush_op('install_drupal', Array)
#19 /Users/rjsteinert/.composer/vendor/drush/drush/commands/core/site_install.drush.inc(289): drush_core_site_install_version(NULL, Array)
#20 [internal function]: drush_core_site_install(NULL)
#21 /Users/rjsteinert/.composer/vendor/drush/drush/includes/command.inc(364): call_user_func_array('drush_core_site...', Array)
#22 /Users/rjsteinert/.composer/vendor/drush/drush/includes/command.inc(215): _drush_invoke_hooks(Array, Array)
#23 [internal function]: drush_command(NULL)
#24 /Users/rjsteinert/.composer/vendor/drush/drush/includes/command.inc(183): call_user_func_array('drush_command', Array)
#25 /Users/rjsteinert/.composer/vendor/drush/drush/includes/command.inc(48): drush_dispatch(Array, Array)
#26 /Users/rjsteinert/.composer/vendor/drush/drush/commands/core/core.drush.inc(975): drush_invoke('site-install', Array)
#27 [internal function]: drush_core_quick_drupal()
#28 /Users/rjsteinert/.composer/vendor/drush/drush/includes/command.inc(364): call_user_func_array('drush_core_quic...', Array)
#29 /Users/rjsteinert/.composer/vendor/drush/drush/includes/command.inc(215): _drush_invoke_hooks(Array, Array)
#30 [internal function]: drush_command()
#31 /Users/rjsteinert/.composer/vendor/drush/drush/includes/command.inc(183): call_user_func_array('drush_command', Array)
#32 /Users/rjsteinert/.composer/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(62): drush_dispatch(Array)
#33 /Users/rjsteinert/.composer/vendor/drush/drush/drush.php(70): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#34 /Users/rjsteinert/.composer/vendor/drush/drush/drush.php(11): drush_main()
#35 {main}
Drupal core install failed.
```

**Comment by mstenta** [comment]
Thanks for the log RJ... I see two lines with errors...

The first looks like it was just a wrong drush command, but you figured that out...

The second, near the bottom, is:

exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1 there is already an index named log_type' in
/Users/rjsteinert/Desktop/farmos/farm/quick-drupal-20151024182516/drupal/includes/database/sqlite/database.inc:238

Did you have farmOS installed previously?  It sort of sounds like it tried to install the database schema, but found that it already existed.  Or something.  Hard to say...

When I use drush make, my command usually looks something like this:

drush make build-farm.make [directory-i-want-it-built-in]

I haven't used the "drush qd" command before.  "drush make" just builds the codebase, though - it doesn't install Drupal - so maybe that's the difference.

Your best bet is to download the pre-built package from http://drupal.org/project/farm - the current stable release is 7.x-1.0-beta6.
