### ISSUE TITLE
FarmOS gives error screen adding ID tag to a Taxonomy

### ISSUE THREAD

**Issue by MarcosCarballal** [farmOS/farmOS#451]
This may just be a bug relating to the Field UI Module and not FarmOS as a whole, but I wouldn't know enough to distinguish between then two.

**Describe the bug**
FarmOS gives error screen ("The website encountered an unexpected error. Please try again later.") on adding an ID Tag to a taxonomy.

After going back to the home page, FarmOS did actually give the ID Tag to the taxonomy.

**To Reproduce**
1. Install the Field UI Module
2. Go to Administration > Structue > Taxonomies
2. Click on Dropdown for 'Materials' and select 'Manage Fields'
3. Add a field, 

**Expected behavior**
If ID tags are not meant to be on Taxonomies, it should not be an option.

If ID tags are meant to be on Taxonomies, it should not display an error screen.

**Screenshots**

**Desktop (please complete the following information):**
- Docker Image: `farmos/farmos:2.x-dev`
- Modules Installed: "Field UI", "Configuration Manager".
 - OS: Ubuntu 20.04
 - Browser: Safari

**Comment by MarcosCarballal** [comment]
Drupal error output
```
www_1  | [Thu Sep 30 17:21:47.997489 2021] [php7:notice] [pid 35] [client 127.0.0.1:45416] Error: Call to a member function get() on null in /opt/drupal/web/profiles/farm/modules/core/id_tag/src/Plugin/Field/FieldWidget/IdTagWidget.php on line 39 #0 /opt/drupal/web/core/lib/Drupal/Core/Field/WidgetBase.php(342): Drupal\\farm_id_tag\\Plugin\\Field\\FieldWidget\\IdTagWidget->formElement(Object(Drupal\\Core\\Field\\FieldItemList), 0, Array, Array, Object(Drupal\\Core\\Form\\FormState))\n#1 /opt/drupal/web/core/lib/Drupal/Core/Field/WidgetBase.php(209): Drupal\\Core\\Field\\WidgetBase->formSingleElement(Object(Drupal\\Core\\Field\\FieldItemList), 0, Array, Array, Object(Drupal\\Core\\Form\\FormState))\n#2 /opt/drupal/web/core/lib/Drupal/Core/Field/WidgetBase.php(111): Drupal\\Core\\Field\\WidgetBase->formMultipleElements(Object(Drupal\\Core\\Field\\FieldItemList), Array, Object(Drupal\\Core\\Form\\FormState))\n#3 /opt/drupal/web/core/lib/Drupal/Core/Field/FieldItemList.php(287): Drupal\\Core\\Field\\WidgetBase->form(Object(Drupal\\Core\\Field\\FieldItemList), Array, Object(Drupal\\Core\\Form\\FormState))\n#4 /opt/drupal/web/core/modules/field_ui/src/Form/FieldConfigEditForm.php(124): Drupal\\Core\\Field\\FieldItemList->defaultValuesForm(Array, Object(Drupal\\Core\\Form\\FormState))\n#5 /opt/drupal/web/core/lib/Drupal/Core/Entity/EntityForm.php(106): Drupal\\field_ui\\Form\\FieldConfigEditForm->form(Array, Object(Drupal\\Core\\Form\\FormState))\n#6 [internal function]: Drupal\\Core\\Entity\\EntityForm->buildForm(Array, Object(Drupal\\Core\\Form\\FormState))\n#7 /opt/drupal/web/core/lib/Drupal/Core/Form/FormBuilder.php(532): call_user_func_array(Array, Array)\n#8 /opt/drupal/web/core/lib/Drupal/Core/Form/FormBuilder.php(278): Drupal\\Core\\Form\\FormBuilder->retrieveForm('field_config_ed...', Object(Drupal\\Core\\Form\\FormState))\n#9 /opt/drupal/web/core/lib/Drupal/Core/Controller/FormController.php(73): Drupal\\Core\\Form\\FormBuilder->buildForm(Object(Drupal\\field_ui\\Form\\FieldConfigEditForm), Object(Drupal\\Core\\Form\\FormState))\n#10 [internal function]: Drupal\\Core\\Controller\\FormController->getContentResult(Object(Symfony\\Component\\HttpFoundation\\Request), Object(Drupal\\Core\\Routing\\RouteMatch))\n#11 /opt/drupal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array)\n#12 /opt/drupal/web/core/lib/Drupal/Core/Render/Renderer.php(573): Drupal\\Core\\EventSubscriber\\EarlyRenderingControllerWrapperSubscriber->Drupal\\Core\\EventSubscriber\\{closure}()\n#13 /opt/drupal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\\Core\\Render\\Renderer->executeInRenderContext(Object(Drupal\\Core\\Render\\RenderContext), Object(Closure))\n#14 /opt/drupal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\\Core\\EventSubscriber\\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array)\n#15 /opt/drupal/vendor/symfony/http-kernel/HttpKernel.php(158): Drupal\\Core\\EventSubscriber\\EarlyRenderingControllerWrapperSubscriber->Drupal\\Core\\EventSubscriber\\{closure}()\n#16 /opt/drupal/vendor/symfony/http-kernel/HttpKernel.php(80): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)\n#17 /opt/drupal/web/modules/simple_oauth/src/HttpMiddleware/BasicAuthSwap.php(67): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#18 /opt/drupal/web/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Drupal\\simple_oauth\\HttpMiddleware\\BasicAuthSwap->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#19 /opt/drupal/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\\Core\\StackMiddleware\\Session->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#20 /opt/drupal/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\\Core\\StackMiddleware\\KernelPreHandle->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#21 /opt/drupal/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\\Core\\StackMiddleware\\ReverseProxyMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#22 /opt/drupal/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\\Core\\StackMiddleware\\NegotiationMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#23 /opt/drupal/web/core/lib/Drupal/Core/DrupalKernel.php(706): Stack\\StackedHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#24 /opt/drupal/web/index.php(19): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#25 {main}, referer: http://localhost/admin/structure/taxonomy/manage/material/overview/fields/taxonomy_term.material.field_material_id/storage?destinations%5B0%5D%5Broute_name%5D=entity.field_config.taxonomy_term_field_edit_form&destinations%5B0%5D%5Broute_parameters%5D%5Bfield_config%5D=taxonomy_term.material.field_material_id&destinations%5B0%5D%5Broute_parameters%5D%5Btaxonomy_vocabulary%5D=material&destinations%5B1%5D%5Broute_name%5D=entity.taxonomy_term.field_ui_fields&destinations%5B1%5D%5Broute_parameters%5D%5Bfield_config%5D=taxonomy_term.material.field_material_id&destinations%5B1%5D%5Broute_parameters%5D%5Btaxonomy_vocabulary%5D=material&destinations%5B2%5D=/admin/structure/taxonomy/manage/material/overview/fields/add-field

```

**Comment by mstenta** [comment]
Thanks for the report @MarcosCarballal !

> If ID tags are not meant to be on Taxonomies, it should not be an option.

Indeed the ID Tag field is designed for use on `asset` entities, and so it probably has some assumptions baked into the code that are causing this.

I agree it shouldn't appear as an option on other entity types. Either that, or we should generalize it so that it does work.

I'm curious: do you have a particular use-case in mind for adding it to a taxonomy? That might inform the direction we take in fixing this...

**Comment by MarcosCarballal** [comment]
In an effort to map as closely as possible to the MSSQL, I thought that the ID tag would be a good way to replace the primary key on my table. However, there are definitely other, probably better options.

My guess it that there is probably not a use case that would **require** ID tags to achieve their design goalse

**Comment by mstenta** [comment]
Ah gotcha! You might want something like a plain number ID then.

The "ID Tag" field type is probably not a great name for it - but it's more complicated than what you need. :-)

It's basically a field type that stores three sub-values: "ID Value", "Tag Type", and "Tag Location". It was originally designed for recording livestock ID tags, so you could say "this cow has an ear tag #101 on the left ear". In farmOS 2.x we generalized it so that it works on other asset types too, beyond animals. For example: QR codes that you print out and stick on equipment, or a stake in the ground, etc etc.

**Comment by MarcosCarballal** [comment]
Ah okay!

I misunderstood. I would assume the simplest solution would be to just not display the option on Taxonomies.

**Comment by mstenta** [comment]
Fixed! I added the `no_ui = TRUE` option to the `IdTagItem` field type annotation - which will prevent this field type from being displayed as an option in the UI. This should prevent confusion about what it's for, since it's really a specific internal field type that is only intended for use with assets.

Thanks again for reporting this @MarcosCarballal !
