### ISSUE TITLE
Error: Call to a member function get() on null in ContentEntityGeometryNormalizer.php on line 64

### ISSUE THREAD

**Issue by mstenta** [farmOS/farmOS#493]
Saw this error in Farmier server logs. Recording here for future investigation... not sure the exact steps to reproduce but the stack trace below might tell us:

```
Error: Call to a member function get() on null in /opt/drupal/web/profiles/farm/modules/core/geo/src/Normalizer/ContentEntityGeometryNormalizer.php on line 64
#0 /opt/drupal/vendor/symfony/serializer/Serializer.php(153): Drupal\\farm_geo\\Normalizer\\ContentEntityGeometryNormalizer->normalize(Array, 'geometry_kml', Array)\n
#1 /opt/drupal/vendor/symfony/serializer/Serializer.php(126): Symfony\\Component\\Serializer\\Serializer->normalize(Array, 'geometry_kml', Array)\n
#2 /opt/drupal/web/profiles/farm/modules/core/kml/src/Plugin/Action/EntityKml.php(97): Symfony\\Component\\Serializer\\Serializer->serialize(Array, 'geometry_kml', Array)\n
#3 /opt/drupal/web/core/modules/system/src/Entity/Action.php(129): Drupal\\farm_kml\\Plugin\\Action\\EntityKml->executeMultiple(Array)\n
#4 /opt/drupal/web/core/modules/views/src/Plugin/views/field/BulkForm.php(415): Drupal\\system\\Entity\\Action->execute(Array)\n
#5 /opt/drupal/web/core/modules/views/src/Form/ViewsFormMainForm.php(183): Drupal\\views\\Plugin\\views\\field\\BulkForm->viewsFormSubmit(Array, Object(Drupal\\Core\\Form\\FormState))\n
#6 /opt/drupal/web/core/modules/views/src/Form/ViewsForm.php(187): Drupal\\views\\Form\\ViewsFormMainForm->submitForm(Array, Object(Drupal\\Core\\Form\\FormState))\n
#7 [internal function]: Drupal\\views\\Form\\ViewsForm->submitForm(Array, Object(Drupal\\Core\\Form\\FormState))\n
#8 /opt/drupal/web/core/lib/Drupal/Core/Form/FormSubmitter.php(114): call_user_func_array(Array, Array)\n
#9 /opt/drupal/web/core/lib/Drupal/Core/Form/FormSubmitter.php(52): Drupal\\Core\\Form\\FormSubmitter->executeSubmitHandlers(Array, Object(Drupal\\Core\\Form\\FormState))\n
#10 /opt/drupal/web/core/lib/Drupal/Core/Form/FormBuilder.php(592): Drupal\\Core\\Form\\FormSubmitter->doSubmitForm(Array, Object(Drupal\\Core\\Form\\FormState))\n
#11 /opt/drupal/web/core/lib/Drupal/Core/Form/FormBuilder.php(320): Drupal\\Core\\Form\\FormBuilder->processForm('views_form_farm...', Array, Object(Drupal\\Core\\Form\\FormState))\n
#12 /opt/drupal/web/core/lib/Drupal/Core/Form/FormBuilder.php(219): Drupal\\Core\\Form\\FormBuilder->buildForm(Object(Drupal\\views\\Form\\ViewsForm), Object(Drupal\\Core\\Form\\FormState))\n
#13 /opt/drupal/web/core/modules/views/src/Plugin/views/display/DisplayPluginBase.php(2270): Drupal\\Core\\Form\\FormBuilder->getForm(Object(Drupal\\views\\Form\\ViewsForm), Object(Drupal\\views\\ViewExecutable), Array)\n
#14 [internal function]: Drupal\\views\\Plugin\\views\\display\\DisplayPluginBase->elementPreRender(Array)\n
#15 /opt/drupal/web/core/lib/Drupal/Core/Security/DoTrustedCallbackTrait.php(101): call_user_func_array(Array, Array)\n
#16 /opt/drupal/web/core/lib/Drupal/Core/Render/Renderer.php(772): Drupal\\Core\\Render\\Renderer->doTrustedCallback(Array, Array, 'Render #pre_ren...', 'exception', 'Drupal\\\\Core\\\\Ren...')\n
#17 /opt/drupal/web/core/lib/Drupal/Core/Render/Renderer.php(363): Drupal\\Core\\Render\\Renderer->doCallback('#pre_render', Array, Array)\n
#18 /opt/drupal/web/core/lib/Drupal/Core/Render/Renderer.php(435): Drupal\\Core\\Render\\Renderer->doRender(Array)\n
#19 /opt/drupal/web/core/lib/Drupal/Core/Render/Renderer.php(201): Drupal\\Core\\Render\\Renderer->doRender(Array, false)\n
#20 /opt/drupal/web/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(241): Drupal\\Core\\Render\\Renderer->render(Array, false)\n
#21 /opt/drupal/web/core/lib/Drupal/Core/Render/Renderer.php(564): Drupal\\Core\\Render\\MainContent\\HtmlRenderer->Drupal\\Core\\Render\\MainContent\\{closure}()\n
#22 /opt/drupal/web/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(242): Drupal\\Core\\Render\\Renderer->executeInRenderContext(Object(Drupal\\Core\\Render\\RenderContext), Object(Closure))\n
#23 /opt/drupal/web/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(132): Drupal\\Core\\Render\\MainContent\\HtmlRenderer->prepare(Array, Object(Symfony\\Component\\HttpFoundation\\Request), Object(Drupal\\Core\\Routing\\CurrentRouteMatch))\n
#24 /opt/drupal/web/core/lib/Drupal/Core/EventSubscriber/MainContentViewSubscriber.php(90): Drupal\\Core\\Render\\MainContent\\HtmlRenderer->renderResponse(Array, Object(Symfony\\Component\\HttpFoundation\\Request), Object(Drupal\\Core\\Routing\\CurrentRouteMatch))\n
#25 [internal function]: Drupal\\Core\\EventSubscriber\\MainContentViewSubscriber->onViewRenderArray(Object(Symfony\\Component\\HttpKernel\\Event\\ViewEvent), 'kernel.view', Object(Drupal\\Component\\EventDispatcher\\ContainerAwareEventDispatcher))\n
#26 /opt/drupal/web/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(142): call_user_func(Array, Object(Symfony\\Component\\HttpKernel\\Event\\ViewEvent), 'kernel.view', Object(Drupal\\Component\\EventDispatcher\\ContainerAwareEventDispatcher))\n
#27 /opt/drupal/vendor/symfony/http-kernel/HttpKernel.php(163): Drupal\\Component\\EventDispatcher\\ContainerAwareEventDispatcher->dispatch(Object(Symfony\\Component\\HttpKernel\\Event\\ViewEvent), 'kernel.view')\n
#28 /opt/drupal/vendor/symfony/http-kernel/HttpKernel.php(80): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)\n
#29 /opt/drupal/web/modules/simple_oauth/src/HttpMiddleware/BasicAuthSwap.php(67): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n
#30 /opt/drupal/web/core/lib/Drupal/Core/StackMiddleware/Session.php(58): Drupal\\simple_oauth\\HttpMiddleware\\BasicAuthSwap->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n
#31 /opt/drupal/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(48): Drupal\\Core\\StackMiddleware\\Session->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n
#32 /opt/drupal/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(48): Drupal\\Core\\StackMiddleware\\KernelPreHandle->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n
#33 /opt/drupal/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(51): Drupal\\Core\\StackMiddleware\\ReverseProxyMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n
#34 /opt/drupal/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\\Core\\StackMiddleware\\NegotiationMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n
#35 /opt/drupal/web/core/lib/Drupal/Core/DrupalKernel.php(708): Stack\\StackedHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n
#36 /opt/drupal/web/index.php(19): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n
```

**Comment by mstenta** [comment]
Seems like we might just want to add this:

```
// If the geofield is empty, bail.
if ($entity->get($geofield)->isEmpty()) {
  continue;
}
```

... before line 63:

https://github.com/farmOS/farmOS/blob/e834a8c84e77a99407097b68325cc1dcc287cc16/modules/core/geo/src/Normalizer/ContentEntityGeometryNormalizer.php#L63

**Comment by mstenta** [comment]
Reading through the trace above, my guess is the user tried to use the bulk KML export action on an asset/log that had an empty geometry.

**Comment by mstenta** [comment]
I created a draft pull request to fix this: https://github.com/farmOS/farmOS/pull/496

I have *not* yet tested to see if the suspected cause is correct:

> my guess is the user tried to use the bulk KML export action on an asset/log that had an empty geometry.

Nor have I confirmed that this PR fixes it. Just pushing the bit of code I had started locally so it doesn't get lost in the meantime...

We may also want to add a test for this.

**Comment by mstenta** [comment]
I confirmed the steps to reproduce. It happens when you try to run the "Export KML" action on a log that doesn't have any geometry.

I also confirmed that my suggested fix resolves it.
